"""Language model request object."""

from typing import Any

from pydantic import BaseModel

from meadow.agent.schema import ChatMessage


class Request(BaseModel):
    """Request object."""

    # Chat prompt
    prompt: list[dict[str, str]]

    # Engine
    engine: str

    # Number responses
    n: int = 1

    # Seed
    seed: int | None = None

    # Temperature for generation
    temperature: float = 0.7

    # Max tokens for generation
    max_tokens: int = 100

    # Nucleus sampling taking top_p probability mass tokens
    top_p: float = 1.0

    # Top k sampling taking top_k highest probability tokens
    top_k: int = 50

    # Stop sequences
    stop: list[str] | None = None

    # Penalize resence
    presence_penalty: float = 0

    # Penalize frequency
    frequency_penalty: float = 0

    # Response format
    # { "type": "json_object" } for JSON output
    response_format: dict[str, str] | None = None

    # Tools
    tools: list[dict[str, Any]] | None = None


class Usage(BaseModel):
    completion_tokens: int
    """Number of tokens in the generated completion."""

    prompt_tokens: int
    """Number of tokens in the prompt."""

    total_tokens: int
    """Total number of tokens used in the request (prompt + completion)."""


class Choice(BaseModel):
    """A single text response made by the model."""

    index: int
    """The index of the choice in the list of choices."""

    message: ChatMessage
    """A chat completion message generated by the model."""


class Response(BaseModel):
    """Chat completion response modelled from OpenAI."""

    id: str
    """A unique identifier for the chat completion."""

    cached: bool
    """Whether the response was retrieved from the cache."""

    choices: list[Choice]
    """A list of chat completion choices.

    Can be more than one if `n` is greater than 1.
    """

    created: int
    """The Unix timestamp (in seconds) of when the chat completion was created."""

    engine: str
    """The model used for the chat completion."""

    usage: Usage | None = None
    """Usage statistics for the completion request."""
