"""Agent schema classes."""

from typing import Literal

from pydantic import BaseModel


class ToolCall(BaseModel):
    """Model response for which tool to call."""

    """
    The arguments to call the function with, as generated by the model in JSON
    format. Note that the model does not always generate valid JSON.
    """
    arguments: str

    """The name of the function to call."""
    name: str


class ChatMessage(BaseModel):
    """The contents of the message."""

    content: str | None = None

    """The role of the author of this message."""
    role: Literal["assistant", "user", "system"]

    """The tool calls generated by the model."""
    tool_calls: list[ToolCall] | None = None
