"""Agent schema classes."""

from typing import Literal

from pydantic import BaseModel


class Function(BaseModel):
    arguments: str
    """
    The arguments to call the function with, as generated by the model in JSON
    format. Note that the model does not always generate valid JSON.
    """

    name: str
    """The name of the function to call."""


class ChatMessage(BaseModel):
    content: str | None = None
    """The contents of the message."""

    role: Literal["assistant", "user", "system"]
    """The role of the author of this message."""

    tool_calls: list[Function] | None = None
    """The tool calls generated by the model."""
